### PR TITLE
Add initial repo structure and PR template

### PR DESCRIPTION
**Pull request by olhakonst17**
## Overview

This PR:
- Adds initial repo structure with .gitkeep placeholder files
- Updates initial README with information on repo structure
- Adds PR template

### References
#[410](https://github.com/cse-labs/distributed-az-edge-framework/issues/410)

### CODE REVIEW

**Review by madossan01 — COMMENTED** [review]
Great to see the repo folders. Thank you for the initiative of bringing also the PR template.
Quick questions about folder structure: When seeing low-code and pro-code as folders, can I assume that low-code would contain scripts related to the AIO Portal and Pro-code anything related to everything else that does not ave a UI to set it? 
Additionally, I'd like suggest to add the .gitignore and add the file .gitkeep to it.

**Review by mahomedalid — APPROVED** [review]

**Comment by olhakonst17** [comment]
> Great to see the repo folders. Thank you for the initiative of bringing also the PR template. Quick questions about folder structure: When seeing low-code and pro-code as folders, can I assume that low-code would contain scripts related to the AIO Portal and Pro-code anything related to everything else that does not have a UI to set it?

@madossan01 Regarding this part - I think somewhere in our documentation I saw approach of referring to AIO Data Processor implementation as low-code, and custom code (e.g. in C#) implementation as pro-code. If you have other ideas of how to better structure this would be happy to adjust to it.

**Comment by olhakonst17** [comment]
> Additionally, I'd like suggest to add the .gitignore and add the file .gitkeep to it.

Could you please elaborate on the goal this action? We already have .gitignore file that was created automatically with the repo. But adding a .gitkeep to it would not allow us to create new empty folders if needed.

**Comment by madossan01** [comment]
About low-code, the term is indeed used to reference services that encapsulates the coding part into UI or other means. This is the case for AIO Portal services. In our case, everything will be pro-code as we are evaluating the low-code part of AIO using a pro-code approach. If the intention is to separate this code that resolved things on low-code part, that is perfectly fine to keep the folders.

About the empty structure and .gitignore, got your point. We just need to remove once we start pushing files.

**Review by madossan01 — APPROVED** [review]

**Pull request merged**
